### ISSUE TITLE
Error in console if attributionController is undefined

### ISSUE THREAD

**Issue by lucasprograms** [rowanwins/mapbox-gl-arcgis-featureserver#1]
In my application the `attributionController` is undefined. That results in a console error (but no other issues I am aware of). Do you think it makes sense to add
```js
if (!attributionController) return;
```
inside the `_setAttribution` method?

**Comment by rowanwins** [comment]
Good idea @lucasprograms

**Comment by rowanwins** [comment]
Resolved by #2
