### ISSUE TITLE
ESRI Authentication Callback

### ISSUE THREAD

**Issue by ssontag55** [rowanwins/mapbox-gl-arcgis-featureserver#7]
@rowanwins Would you recommend adding it here:
https://github.com/rowanwins/mapbox-gl-arcgis-featureserver/blob/master/src/main.js#L421

And then setting token in the options after user logs in?

Similar to this:
https://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html

**Comment by rowanwins** [comment]
@ssontag55 
The library doesn't handle generating a token or doing the callback side of things, that logic belongs to the broader application. This library does however support appending tokens to requests that it makes.

Once you've generated your token it can be added as an option using the `token` parameter during the creation of the layer. 
````
    const fsSourceId = 'featureserver-src'

    const service = new FeatureService(fsSourceId, map, {
      url: '.../FeatureServer/0',
      token: 'xyz'
    })
`````

Alternatively you can also set the token using the `setToken` method if you get the token after your layer has been initiated.
````
    const fsSourceId = 'featureserver-src'

    const service = new FeatureService(fsSourceId, map, {
      url: '.../FeatureServer/0'
    })
    
    function gotTheTokenSomehow (myRetrievedToken) {
        service.setToken(myRetrievedToken)
    }
`````
